In [2]:
import numpy as np

In [194]:
#Columns = Age MathsMarks ScienceMarks
data = np.array([
    [18, 85, 78], #Student1
    [19, 92, 88], #Student2
    [17, 95, 75], #Student3
    [18, 65, 70], #Student4
    [19, 90, 85]  #Student5
])
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 95, 75],
       [18, 65, 70],
       [19, 90, 85]])

In [195]:
#Get the shpae of data
np.shape(data)  #or data.shape

(5, 3)

In [196]:
#Get teh mean of age
a = data[0:, 0]
np.mean(a)

np.float64(18.2)

In [197]:
#Extract maths marks of all students
mm = data[:, 1]
mm

array([85, 92, 95, 65, 90])

In [198]:
#Get details of students whose mm > 90
data[mm > 90]

array([[19, 92, 88],
       [17, 95, 75]])

In [199]:
#Increase maths marks of all students by 5
mm+5

array([ 90,  97, 100,  70,  95])

In [200]:
#Get maximum of maths marks'
np.max(mm)

np.int64(95)

In [201]:
#Get average of maths marks
np.mean(mm)

np.float64(85.4)

In [202]:
#Extract science marks of all students
sm = data[0:, 2]
sm

array([78, 88, 75, 70, 85])

In [203]:
#Get maximum of science marks
np.max(sm)

np.int64(88)

In [204]:
#Find how many students are younger than 19
# count = 0
# for i in a:
#     if i < 19:
#         count += 1
# print(f"Number of student younger than 19 is: {count}")

len(data[a < 19])

3

In [205]:
#Calculate the average marks in each subject (column-wise)
tm = data[:,1:3]
np.mean(tm, axis = 0)

array([85.4, 79.2])

In [206]:
data[(data[0:,1] >= 80) & (data[0:,2] >= 80)]

array([[19, 92, 88],
       [19, 90, 85]])

In [207]:
#Replace all science marks < 75 with 0
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 95, 75],
       [18, 65,  0],
       [19, 90, 85]])

In [ ]:
"""VALID SUDOKOU"""
#For a valid sudoku the sum of each row and column must be 45 and sum of every 3,3 matrix also must be 45

In [46]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [47]:
a = np.sum(s,axis = 1)
for i in a:
    if i != 45:
        print("Sudoku is not valid")
        break
else :
    print("for rows sudoku is valid")

for rows sudoku is valid


In [48]:
b = np.sum(s,axis = 0)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break
else :
    print("for columns sudoku is valid")

for columns sudoku is valid


In [50]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]
        print(n.sum())
        if n.sum() != 45:
            print("Your Sudoku is not valid ")
else:
    print("Your sudoku is valid")

45
45
45
45
45
45
45
45
45
Your sudoku is valid
