In [113]:
import numpy as np

In [114]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [115]:
"""Array Generation function:-
1. arange()
2. zeros()
3. ones()
4. linspace()"""

'Array Generation function:-\n1. arange()\n2. zeros()\n3. ones()\n4. linspace()'

In [116]:
"""array generation function for vector example"""

'array generation function for vector example'

In [117]:
b = np.arange(1,11,2)
b

array([1, 3, 5, 7, 9])

In [118]:
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [119]:
d = np.ones(5)
d

array([1., 1., 1., 1., 1.])

In [120]:
e = np.linspace(1,11,4)
e

array([ 1.        ,  4.33333333,  7.66666667, 11.        ])

In [121]:
f = np.linspace(1,5,3)
f

array([1., 3., 5.])

In [122]:
g = np.linspace(1,5,5)
g

array([1., 2., 3., 4., 5.])

In [123]:
"""Array generation functions for matrix examples"""

'Array generation functions for matrix examples'

In [124]:
h = np.zeros((3,3))
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [125]:
i = np.ones((3,3))
i

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [126]:
j = np.ones((6,3))
j

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
"""Random generation function 
1. standarized (-3,3) = random.randn()
2. normalize (-1,1) = randon.rand()
3. any integer from -infinity to +infinity"""

'Random generation function \n1. standarized (-3,3) = random.randn()\n2. normalize (-1,1) = randon.rand()\n3. any integer from -infinity to +infinity'

In [128]:
k = np.random.rand(15)
k

array([0.00358771, 0.83745477, 0.64050789, 0.83680587, 0.42166607,
       0.51517455, 0.29584484, 0.45803921, 0.03291365, 0.57296728,
       0.89759142, 0.86060663, 0.81769844, 0.74585171, 0.78491913])

In [129]:
l = np.random.randn(10)
l

array([-1.284066  ,  1.56839653, -0.69155549,  0.82276185,  0.55503119,
       -0.51221375, -1.22623497,  0.91235945, -0.76173338, -0.44587595])

In [130]:
m = np.random.randint(10,30,10)
m

array([16, 27, 14, 25, 14, 27, 22, 26, 10, 22], dtype=int32)

In [131]:
#Array attributes

In [132]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
arr.shape

(3, 3)

In [134]:
arr.size

9

In [135]:
arr.dtype

dtype('int64')

In [136]:
#Array methods

In [137]:
a = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [138]:
a.min()

np.int64(1)

In [139]:
a.max()

np.int64(12)

In [140]:
a.sum()

np.int64(78)

In [141]:
np.sum(a,axis = 0)  #axis = 0 means column

array([15, 18, 21, 24])

In [142]:
np.sum(a,axis = 1)  #axis = 1 means row

array([10, 26, 42])

In [143]:
a.mean()

np.float64(6.5)

In [144]:
a.std()

np.float64(3.452052529534663)

In [145]:
a.argmin()  #index of minimum element

np.int64(0)

In [146]:
a.argmax()  #index of maximum element

np.int64(11)

In [147]:
#Reshaping and Resizing

In [148]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [149]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [150]:
""" Numpy indexing and slicing of vectors"""

' Numpy indexing and slicing of vectors'

In [151]:
ar = np.arange(11,21)
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [152]:
ar[1:5:1]  #Slicing

array([12, 13, 14, 15])

In [153]:
ar[2]  #Indexing 

np.int64(13)

In [154]:
"""Numpy Indexing and Slicing for Matrix"""

'Numpy Indexing and Slicing for Matrix'

In [155]:
mat = np.arange(1,31).reshape(6,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [156]:
mat[0,4]  #Indexing in matrix

np.int64(5)

In [157]:
mat[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [158]:
mat[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [159]:
"""Boolean Indexing"""

'Boolean Indexing'

In [160]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [161]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [162]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [163]:
"""Numpy array operation
1. Arithmetic 
2. Broadcasting
4. Deep and Shallow copy
5. Matrix operations
6. Advance array manipulation
a. Stacking array
b. Splitting array"""

'Numpy array operation\n1. Arithmetic \n2. Broadcasting\n4. Deep and Shallow copy\n5. Matrix operations\n6. Advance array manipulation\na. Stacking array\nb. Splitting array'

In [164]:
#Arithmetic operations

In [165]:
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)
arr1 , arr2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]))

In [166]:
arr1 + arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [167]:
arr1 * arr2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [168]:
arr1 - arr2


array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [169]:
arr1 / arr2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [170]:
arr1 // arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [171]:
arr1 ** arr2

array([                  1,                4096,             1594323,
                 268435456,         30517578125,       2821109907456,
           232630513987207,   18014398509481984, 1350851717672992089,
       7766279631452241920])

In [172]:
arr1 % arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr1 = np.arange(1,26).reshape(5,5)
arr2 = np.arange(1,26).reshape(5,5)
arr1, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]]))

In [174]:
arr1 + arr2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [175]:
arr1 - arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [176]:
arr1 * arr2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

In [177]:
arr1 / arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [178]:
arr1 // arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [179]:
arr1 ** arr2

array([[                   1,                    4,                   27,
                         256,                 3125],
       [               46656,               823543,             16777216,
                   387420489,          10000000000],
       [        285311670611,        8916100448256,      302875106592253,
           11112006825558016,   437893890380859375],
       [                   0, -2863221430593058543,  -497033925936021504,
         6353754964178307979, -2101438300051996672],
       [-1595931050845505211,  4981753131911086080,  8450172506621111015,
                           0, -6776596920136667815]])

In [180]:
arr1 % arr2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [181]:
#Braadcasting

In [182]:
arr1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [183]:
arr1 - 5

array([[-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [184]:
"""Deep and shallow copy"""

'Deep and shallow copy'

In [185]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [186]:
slice = a[:5]
slice = slice*10          #Shallow copy
slice ,a

(array([10, 20, 30, 40, 50]), array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [187]:
a = np.arange(1,11)
b = a
b[0] = 77               #Deep copy
a, b

(array([77,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([77,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [188]:
a = np.arange(5,16)
b = a.copy()
b[0] = 77
b , a

(array([77,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

In [189]:
"""Matrix operation"""

'Matrix operation'

In [190]:
# Multiplication
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [191]:
a @ b

array([[19, 22],
       [43, 50]])

In [192]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [193]:
#Transponse
a.T , b.T

(array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]))

In [194]:
"""Array Manipulation
1. Stack Array
a. Vertical stacking
b. Horizonal stacking
c. column stacking"""
#Stacking can be done on vectors only not on matrix

'Array Manipulation\n1. Stack Array\na. Vertical stacking\nb. Horizonal stacking\nc. column stacking'

In [195]:
a = np.arange(1,6)
b = np.arange(6,11)
a,b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [196]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [197]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [198]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [199]:
"""Array Manipulation
1. Spliting Array
a. Vertical spliting
b. Horizonal spliting"""

'Array Manipulation\n1. Spliting Array\na. Vertical spliting\nb. Horizonal spliting'

In [200]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [203]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [205]:
np.hsplit(a,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [204]:
np.vsplit(a,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [206]:
np.vsplit(a,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [210]:
b = np.vsplit(a,2)
for i in b:
    print(i)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
